//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Numerics.Entity
{
    internal partial class LegalEntity
    {
        public LegalEntity()
        {
            this.Book = new HashSet<Book>();
        }
    
        public int ID { get; set; }
    
        internal virtual ICollection<Book> Book { get; set; }
        internal virtual Currency Currency { get; set; }
    }
    
}
