//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace Numerics.Entity
{
    public partial class NumericsContext : DbContext
    {
        public NumericsContext()
            : base("name=NumericsContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        internal DbSet<Product> Products { get; set; }
        internal DbSet<Asset> Assets { get; set; }
        internal DbSet<Position> Positions { get; set; }
        internal DbSet<ProductFamily> ProductFamilies { get; set; }
        internal DbSet<ProductSubFamily> ProductSubFamilies { get; set; }
        internal DbSet<Counterparty> Counterparties { get; set; }
        internal DbSet<Price> Prices { get; set; }
        internal DbSet<Trade> Trades { get; set; }
        internal DbSet<CashEvent> CashEvents { get; set; }
        internal DbSet<LegalEntity> LegalEntities { get; set; }
        internal DbSet<Book> Books { get; set; }
        internal DbSet<CashFlow> CashFlows { get; set; }
        internal DbSet<Currency> Currencies { get; set; }
    }
}
