//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Numerics.Entity
{
    public partial class Product
    {
        public int ID { get; set; }
        public int ProductSubFamilyID { get; set; }
    
        internal virtual ProductSubFamily SubFamily { get; set; }
    }
    
}
